# Generated by Django 2.1.4 on 2018-12-11 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('city', models.CharField(max_length=32)),
                ('street', models.CharField(max_length=64)),
                ('postal_code', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('pin_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='SensorProvides',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField(max_length=512)),
                ('eula_url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Apartment')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Service')),
            ],
        ),
        migrations.AddField(
            model_name='sensor',
            name='provides',
            field=models.ManyToManyField(to='core.SensorProvides'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='sensors',
            field=models.ManyToManyField(to='core.Sensor'),
        ),
    ]
