# Generated by Django 2.1.4 on 2018-12-19 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorprovides',
            name='description',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='requires',
            field=models.ManyToManyField(to='core.ServiceRequirement'),
        ),
        migrations.AddField(
            model_name='servicerequirement',
            name='description',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
