# Generated by Django 2.1.4 on 2018-12-27 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181219_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='benefit_long',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='benefit_short',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='price',
            field=models.CharField(default='Free', max_length=8),
            preserve_default=False,
        ),
    ]
