# Generated by Django 2.1.4 on 2019-01-09 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190107_1611'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('user', 'service')},
        ),
    ]
