# Generated by Django 2.1.4 on 2019-01-02 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20181227_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='provides',
        ),
        migrations.RemoveField(
            model_name='service',
            name='requires',
        ),
        migrations.DeleteModel(
            name='SensorProvides',
        ),
        migrations.DeleteModel(
            name='ServiceRequirement',
        ),
    ]
