# Generated by Django 2.1.4 on 2019-01-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190102_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name_plural': 'Sensor Attributes',
            },
        ),
        migrations.AddField(
            model_name='sensor',
            name='provides',
            field=models.ManyToManyField(to='core.SensorAttribute'),
        ),
        migrations.AddField(
            model_name='service',
            name='requires',
            field=models.ManyToManyField(to='core.SensorAttribute'),
        ),
    ]
