# Generated by Django 2.1.4 on 2019-01-10 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190110_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='postal_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='apartmentsensor',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartment_sensors', to='core.Apartment'),
        ),
        migrations.AlterField(
            model_name='apartmentsensorvalue',
            name='apartment_sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartment_sensor_values', to='core.ApartmentSensor'),
        ),
    ]
