# Generated by Django 2.1.4 on 2019-01-02 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190102_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='pin_code',
        ),
    ]
