# Generated by Django 2.1.4 on 2019-01-15 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190110_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorattribute',
            name='name',
            field=models.CharField(default='sensor', max_length=128),
        ),
        migrations.AddField(
            model_name='sensorattribute',
            name='serial_number',
            field=models.CharField(default='T-800', max_length=128),
        ),
    ]
