# Generated by Django 2.1.4 on 2019-01-16 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_sensorattribute_sensortype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensorattribute',
            old_name='sensorType',
            new_name='sensor_type',
        ),
    ]
