# Generated by Django 2.1.4 on 2019-01-16 15:50
import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190116_0904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensorattribute',
            name='sensor_type',
        ),
        migrations.RemoveField(
            model_name='sensorattribute',
            name='serial_number',
        ),
        migrations.AddField(
            model_name='apartmentsensor',
            name='identifier',
            field=models.CharField(default=uuid.uuid4, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
