# Generated by Django 2.1.4 on 2019-01-16 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20190116_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensorattribute',
            name='name',
        ),
    ]
