# Generated by Django 2.1.4 on 2019-01-22 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_sensorattribute_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorattribute',
            name='ui_type',
            field=models.CharField(choices=[('TEMPERATURE', 'Temperature'), ('HUMIDITY', 'Humidity'), ('CO2', 'Co2'), (None, 'Other')], max_length=128, null=True),
        ),
    ]
