# Generated by Django 2.1.4 on 2019-01-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_sensorattribute_ui_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='name',
            field=models.CharField(default='NAME-HERE', max_length=64),
            preserve_default=False,
        ),
    ]
